name: WebdriverIO Cross-OS App Test

on:
  workflow_dispatch:
    inputs:
      RUNNING_OS:
        description: 'OS running test (win, mac, linux)'
        required: true
        default: 'win'

      EXE_URL:
        description: 'Enter EXE installer URL'
        required: true
        default: 'https://delta.jan.ai/nightly/Jan-nightly_0.5.17-319_x64-setup.exe'

      APP_PATH:
        description: "Installed app path (e.g. C:\\Program Files\\Jan-nightly\\Jan-nightly.exe)"
        required: true
        default: "C:\\Users\\runneradmin\\AppData\\Local\\Programs\\Jan-nightly\\Jan-nightly.exe"

      BUNDLE_ID:
        description: 'App bundle ID or identifier'
        required: false
        default: "C:\\Users\\runneradmin\\AppData\\Local\\Programs\\Jan-nightly\\Jan-nightly.exe"

      ENV:
        description: 'Test environment (e.g. dev, staging)'
        required: true
        default: 'dev'

      TEST_FILES:
        description: 'Test files to run'
        required: true
        default: 'test/specs/test.homePage.ts'

      OPEN_AI:
        description: 'OpenAI API Key'
        required: false
        default: ''

jobs:
  test-on-windows:
    if: ${{ github.event.inputs.RUNNING_OS == 'win' }}
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Appium + Windows Driver
        run: |
          npm install -g appium
          appium driver install windows
          appium -v

      - name: Install test dependencies
        run: |
          cd src-tauri/src/tests
          npm install

      - name: Download and install the app
        run: |
          $installer = "$env:USERPROFILE\AppInstaller.exe"
          Invoke-WebRequest "${{ github.event.inputs.EXE_URL }}" -OutFile $installer
          Start-Process -FilePath $installer -ArgumentList "/silent" -Wait

      - name: Enable Developer Mode (required for WinAppDriver)
        run: |
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"
        shell: powershell

      - name: Start WinAppDriver
        run: |
          Start-Process -FilePath "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"
        shell: powershell

      - name: Start Appium on custom port
        run: |
          taskkill /IM node.exe /F 2>$null
          cmd /C "start /B appium -p 4725"

      - name: Wait for Appium to start
        run: Start-Sleep -Seconds 10

      - name: Create .env for test
        run: |
          echo "APP_PATH=${{ github.event.inputs.APP_PATH }}" > src-tauri/src/tests/.env
          echo "BUNDLE_ID=${{ github.event.inputs.BUNDLE_ID }}" >> src-tauri/src/tests/.env
          echo "RUNNING_OS=${{ github.event.inputs.RUNNING_OS }}" >> src-tauri/src/tests/.env
          echo "TEST_FILES=${{ github.event.inputs.TEST_FILES }}" >> src-tauri/src/tests/.env
          echo "ENV=${{ github.event.inputs.ENV }}" >> src-tauri/src/tests/.env
          echo "OPENAI=${{ github.event.inputs.OPEN_AI }}" >> src-tauri/src/tests/.env

      - name: Run WebdriverIO tests
        run: |
          cd src-tauri/src/tests
          npm run test
