name: Auto QA Test Runner (Legacy)

on:
  push:
    branches:
      - feat/auto-qa
      - main
      - develop
    paths:
      - 'autoqa/**'
      - '.github/workflows/autoqa.yml'

jobs:
  call-autoqa-template:
    uses: ./.github/workflows/autoqa-template.yml
    with:
      jan_app_windows_source: 'https://catalog.jan.ai/windows/Jan-nightly_0.6.4-726_x64-setup.exe'
      jan_app_ubuntu_source: 'https://delta.jan.ai/nightly/Jan-nightly_0.6.4-739_amd64.deb'
      jan_app_macos_source: 'https://delta.jan.ai/nightly/Jan-nightly_0.6.4-739_universal.dmg'
      is_nightly: true
      source_type: 'url'
    secrets:
      RP_TOKEN: ${{ secrets.RP_TOKEN }}
